Senzing/senzingapi-runtime

- Dockerfile
> #1 Remove Python

- .github/dependabot.yml
> #1 Add dependabot instructions

- docker-compose.test.yml
> #6 remove docker-compose.test.yml

- CHANGELOG.md
- Dockerfile
> #6 Update Senzing DEB version

- CHANGELOG.md
- Dockerfile
- README.md
Issue number: #14 & #13
???
???
> Clean up Dockerfile and README

- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- .github/workflows/add-triage-label.yaml
- .github/workflows/build-docker-container.yaml
- .github/workflows/identify-customer.yaml
> #18 Modify workflows

- Dockerfile
> #23 update to use apt-get

- README.md
> Fix dangling license word

- CHANGELOG.md
- Dockerfile
> #31 Prepare for versioned release

- CHANGELOG.md
- Dockerfile
> #40 Prepare for versioned release

- .github/workflows/senzing-cicd-buildtest.yaml
- .github/workflows/senzing-cicd-deploy.yaml
- cicd-deploy/deploy.yml
- cicd-test/test.yml
> #35 Migrate changes from senzingapi-tools

- CHANGELOG.md
- Dockerfile
> #49 Update to senzing 3.6.0

- CHANGELOG.md
- Dockerfile
> #61 Update senzing version

- .github/workflows/docker-push-containers-to-dockerhub.yaml
> #61 remove linux/arm64

- CHANGELOG.md
- Dockerfile
> #61 Revert to 3.7.0

- Dockerfile
- README.md
> 61.dockter.6

- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
> #59 Fix Github actions

- .github/workflows/docker-push-containers-to-dockerhub.yaml
> #59 Add arm64

- .github/CODEOWNERS
- .github/workflows/docker-build-container.yaml
Issue number: Senzing factory/build resources#79
> Senzing factory/build resources#79

- CHANGELOG.md
- Dockerfile
> #78 Prepare for versioned release

- CHANGELOG.md
- Dockerfile
Issue number: senzing-factory/build-resources#110
> senzing-factory/build-resources#110 Prepare for versioned release

- CHANGELOG.md
- Dockerfile
- README.md
> #88 Remove USER 1001

- README.md
> 88 dockter 2

- CHANGELOG.md
- README.md
> #88 Prepare for versioned release

- README.md
> #92 Link to DockerHub

- CHANGELOG.md
- Dockerfile
> #96 Version 3.12.0

- .github/workflows/docker-push-containers-to-dockerhub-beta.yaml
- .github/workflows/docker-push-containers-to-dockerhub-staging.yaml
> #98 Add manual workflow to create senzing/senzingapi-runtime-staging

- CHANGELOG.md
- Dockerfile
> #102 Update to Senzing 3.12.5

- CHANGELOG.md
- Dockerfile
> #104 Update to Senzing 3.12.6

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-senzing-dependabot.yaml
- .github/workflows/add-to-project-senzing.yaml
- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications

- .github/workflows/spellcheck.yaml
- .gitignore
- .vscode/cspell.json
- CHANGELOG.md
Issue number: senzing-factory/build-resources#185
> senzing-factory/build-resources#185 add spellcheck
